'use client'

type TutorialDialogProps = {
  open: boolean
  onClose: () => void
}

const sectionGuides = [
  {
    title: 'Experience',
    body: 'Use one entry per job. Fill job title, company, period, then put each responsibility or achievement on its own detail line.',
  },
  {
    title: 'Education',
    body: 'Use one entry per school, degree, bootcamp, or certification. Details are best for thesis work, honors, coursework, or short context.',
  },
  {
    title: 'Projects',
    body: 'Use one entry per project. Description explains what it does, Stack lists technologies, and Repo / link stores the public URL when available.',
  },
  {
    title: 'Skills',
    body: 'Use category groups such as Languages, Frameworks, Infrastructure, or Tools. Items should stay short and easy to scan.',
  },
  {
    title: 'Personal',
    body: 'Use label and value rows for optional context such as location, nationality, availability, portfolio, or work authorization.',
  },
  {
    title: 'Custom',
    body: 'Use Custom for freeform sections that do not yet have a structured editor, such as a short summary or awards paragraph.',
  },
]

const terms = [
  ['Section', 'A top-level CV block such as Experience, Skills, or Projects.'],
  ['Entry', 'One repeatable item inside a section, such as one job, one school, or one project.'],
  ['Detail line', 'A short line under an entry. These work best as concise outcomes, responsibilities, or context.'],
  ['Group', 'A named skill bucket, for example Languages or Infrastructure.'],
  ['Item', 'One skill inside a group, for example TypeScript or Docker.'],
  ['Row', 'A label and value pair used by Personal sections.'],
  ['Markdown aesthetic', 'The generated visual style that looks like markdown headings, code, timelines, and JSON without asking you to write markdown.'],
  ['JSON mode', 'A machine-readable preview mode that presents the CV as structured JSON-looking content.'],
  ['Semantic colors', 'Colors tied to meaning: role, company, period, heading, category, project title, and similar CV parts.'],
]

const textFormatting = [
  {
    title: 'Bold',
    example: '**Led migration**',
    body: 'Use bold for one important phrase, outcome, or responsibility. It should guide the eye, not decorate every sentence.',
  },
  {
    title: 'Inline code',
    example: '`React Native`',
    body: 'Use code formatting for technologies, commands, libraries, APIs, frameworks, or short technical identifiers.',
  },
  {
    title: 'Line breaks',
    example: 'one detail per line',
    body: 'Details, descriptions, and custom body text preserve intentional line breaks. Separate ideas into short lines.',
  },
  {
    title: 'Generated markers',
    example: '#, ##, ###, timelines',
    body: 'Heading markers, timeline connectors, and JSON punctuation are generated by cvgen. You do not need to type them.',
  },
]

const styleSteps = [
  'Open the Style tab in the left sidebar on desktop. On mobile, open Meta, then choose Style.',
  'Choose Render Mode: md for the markdown-style CV, json for JSON-looking output, or per-section to mix them.',
  'Choose a preset if you want a fast theme baseline.',
  'Pick a font and font size for the whole CV.',
  'Edit base colors for background, text, muted text, links, borders, and code backgrounds.',
  'Edit semantic colors for headings, periods, roles, companies, categories, and project titles.',
  'For one-off section styling, select a section, open its Colors panel in the editor, and override only that section.',
  'Use Preview while editing. Export PDF when the visual layout and copy-paste behavior look right.',
]

function SectionCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded border border-gray-800 bg-gray-950/60 p-3">
      <h3 className="text-xs font-mono text-blue-300 uppercase tracking-wide">{title}</h3>
      <p className="mt-1 text-sm leading-relaxed text-gray-300">{body}</p>
    </div>
  )
}

export function TutorialDialog({ open, onClose }: TutorialDialogProps) {
  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3"
      role="dialog"
      aria-modal="true"
      aria-labelledby="tutorial-title"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      <div className="flex max-h-[90vh] w-full max-w-4xl flex-col rounded border border-gray-700 bg-gray-900 shadow-2xl">
        <div className="flex items-center justify-between gap-3 border-b border-gray-800 px-4 py-3">
          <div>
            <h2 id="tutorial-title" className="text-sm font-mono uppercase tracking-wide text-gray-100">
              cvgen guide
            </h2>
            <p className="mt-1 text-xs text-gray-500">
              Build structured CV content, keep the generated markdown aesthetic, then tune the visual system.
            </p>
          </div>
          <button
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded border border-gray-700 text-gray-400 transition-colors hover:border-gray-500 hover:text-gray-100"
            aria-label="Close guide"
          >
            ×
          </button>
        </div>

        <div className="overflow-y-auto px-4 py-4">
          <div className="space-y-5">
            <section>
              <h3 className="text-xs font-mono uppercase tracking-wide text-gray-500">Section Contents</h3>
              <div className="mt-2 grid gap-2 sm:grid-cols-2">
                {sectionGuides.map((item) => (
                  <SectionCard key={item.title} title={item.title} body={item.body} />
                ))}
              </div>
            </section>

            <section>
              <h3 className="text-xs font-mono uppercase tracking-wide text-gray-500">Formatting Nomenclature</h3>
              <div className="mt-2 overflow-hidden rounded border border-gray-800">
                {terms.map(([term, description]) => (
                  <div key={term} className="grid gap-1 border-b border-gray-800 bg-gray-950/40 px-3 py-2 last:border-b-0 sm:grid-cols-[150px_1fr]">
                    <dt className="text-xs font-mono text-green-300">{term}</dt>
                    <dd className="text-sm leading-relaxed text-gray-300">{description}</dd>
                  </div>
                ))}
              </div>
            </section>

            <section>
              <h3 className="text-xs font-mono uppercase tracking-wide text-gray-500">Text Formatting</h3>
              <div className="mt-2 grid gap-2 sm:grid-cols-2">
                {textFormatting.map((item) => (
                  <div key={item.title} className="rounded border border-gray-800 bg-gray-950/60 p-3">
                    <div className="flex items-center justify-between gap-3">
                      <h3 className="text-xs font-mono text-purple-300 uppercase tracking-wide">{item.title}</h3>
                      <code className="rounded bg-gray-900 px-1.5 py-0.5 text-xs text-green-300">{item.example}</code>
                    </div>
                    <p className="mt-2 text-sm leading-relaxed text-gray-300">{item.body}</p>
                  </div>
                ))}
              </div>
            </section>

            <section>
              <h3 className="text-xs font-mono uppercase tracking-wide text-gray-500">Styling Steps</h3>
              <ol className="mt-2 space-y-2">
                {styleSteps.map((step, index) => (
                  <li key={step} className="flex gap-3 rounded border border-gray-800 bg-gray-950/40 p-3">
                    <span className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded border border-gray-700 text-xs font-mono text-blue-300">
                      {index + 1}
                    </span>
                    <span className="text-sm leading-relaxed text-gray-300">{step}</span>
                  </li>
                ))}
              </ol>
            </section>

            <section className="rounded border border-blue-900/60 bg-blue-950/20 p-3">
              <h3 className="text-xs font-mono uppercase tracking-wide text-blue-300">Good CV Rhythm</h3>
              <p className="mt-1 text-sm leading-relaxed text-gray-300">
                Keep entries compact, make detail lines concrete, and let styles do the visual work. The editor stores structured data first; the markdown look and JSON-friendly export are generated from that structure.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
